### PR TITLE
add secure random number generator as extension

### PR DESCRIPTION
**Pull request by johnxnguyen**
## What's in this PR?

I've added an extension to `UInt` to provide a secure random number generator with an upper bound and no modulo bias. This was suggested by @vytis and I've used [this page](https://medium.com/hownetworks/dont-waste-cycles-with-modulo-bias-35b6fdafcf94) as a guide.

### CODE REVIEW

**Comment by vytis** [comment]
Would be good if @marcoconti83 or @raphaelrobert could check it for any deficiencies.

**Comment by typfel** [comment]
I guess I missed the previous discussion but why can't we use `arc4random_uniform` directly?

**Comment by johnxnguyen** [comment]
@typfel although `arc4random_uniform` is free of modulo bias, I don't think it's really considered random enough for crypto purposes

**Comment by vytis** [comment]
Basically to be on the safe side and use cryptographically safe random numbers. `arc4random` is not safe I think.

**Comment by typfel** [comment]
Ok

**Comment by johnxnguyen** [comment]
Also, I'm not sure how to test this, is there something we can test?

**Comment by marcoconti83** [comment]
What are you going to use this function for? Where do you need a random UInt?

**Comment by johnxnguyen** [comment]
@marcoconti83 when we obfuscate a text message, we use a random array index to replace each non-whitespace character with a random alphabetic character

**Pull request merged**
