### PR TITLE
Added CircleCI integration

### PR DESCRIPTION
**Pull request by vytis**

### CODE REVIEW

**Comment by daehn** [comment]
Wow, 4h after this PR was created and Travis still did not pick it up. A general question, as the `circle.yml` seems to be framework agnostic now, could we also fetch it from `wire-ios-shared-ressource` like we do with the `Dangerfile`?

**Comment by mikeger** [comment]
@daehn @vytis  👍 I like the idea of fetching it, then if we update to xcode 8.3 we don't have to go around and patch the file in every repo.

**Comment by vytis** [comment]
Yeah I was thinking about it, but it might be a bit tricky - the config is read from the repo on pull. So it works slightly differently than Danger which simply reads the config when it is launched.
I need to take a look at the docs, maybe there is some way to do it though. If nothing works we could make a script that fetches it from the `wire-ios-shared-resource` to avoid copy-pasting it...

**Comment by daehn** [comment]
@vytis makes sense, the config has to be there before the actual build starts, so I am unsure if there is a way to achieve this.

**Pull request merged**
