### PR TITLE
[WIP] [Draft] Basic promise chainig

### PR DESCRIPTION
**Pull request by mikeger**
This is to support the basic promise chaining, or even chaining the several async actions, where some of the actions might fail.

Simple example that I've had in my mind could be:
```swift
createBackup >>> requestPassword (self) { result in

}
```
where
```swift
func requestPassword(over controller: UIViewController) -> Promise<Password> { ... }
func createBackup(password: Password, completion: (Result<URL>)->()) { ... }
```

Please add your comments and suggestions, I am open for improving or even reworking it.

### CODE REVIEW

**Comment by daehn** [comment]
I am not sure about writing our own Promise library, maybe we should also look into open source alternatives that provide common methods like map, flatMap, catch, finally, Promise.all and Promise.race.

**Comment by daehn** [comment]
@mikeger I personally think https://github.com/khanlou/Promise is a good and not too big candidate for example.

**Comment by daehn** [comment]
I am also not sure about using `Result` and promises together. The way I see it promises are a way to get rid of the result type. For example a method with the following signature:

```swift
func doAsyncStuff(completion: Result<Foo>)
```

can just return a `Promise<Foo>` in promiseworld, thus stripping the Result type from the signature. The error can then be handled in a `catch` clause, whereas the `Foo` object can be accessed in subsequent actions or promises by using a `then` (or something like that) block.

```swift
func doAsyncStuff() -> Promise<Foo>
```

**Comment by mikeger** [comment]
@daehn I just think it's slightly more convenient to have one callback where it's possible to for example remove loading view or something of a sort and then deal with if it was an error or a success, but yeah if it's not the common practice then may be there is a reason.

**Comment by daehn** [comment]
@mikeger I agree, I think we can achieve a similar result by overloading an operator like you did and internal using the `then` function, maybe something like:

```swift
func >>> <A, B>(a: Promise<A>, a2b: @escaping (A) -> Promise<B>) -> Promise<B> {
    return a.then(b2c)
}
```

**Pull request closed without merging**
