### PR TITLE
fix: build with Xcode 12.4 SQPIT-781

### PR DESCRIPTION
**Pull request by billypchan**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/SQPIT-781" title="SQPIT-781" target="_blank">TaskSQPIT-781</a>  Build frameworks compiles on both Xcode 12 and 13
  </td></table>
  <br />
 

Built with Xcode 12.4 to allow wire-ios to built with Both Xcode 12/13

### CODE REVIEW

**Comment by billypchan** [comment]
release patch

**Comment by billypchan** [comment]
release patch

**Comment by billypchan** [comment]
release patch

**Comment by billypchan** [comment]
release patch

**Comment by billypchan** [comment]
release patch

**Comment by zenkins** [comment]
Hello, @billypchan! Merging PR for command **release patch** for PR #**143**. Will create a **patch** release after merged.
Next version is 44.0.2.

**Pull request merged**
